setup socket and login
deriv-com/smarttrader_archived pull request #21
Opened 2023-10-17 06:20 UTC by henry-deriv

2023-10-18 04:40 UTC, shayan-deriv commented on src/utils/storage.ts
> +    const data = localStorage.getItem('client.accounts');
we can use `getFromStorage()` which is already in this file.

2023-10-18 04:40 UTC, shayan-deriv commented on src/utils/storage.ts
> +    const active_loginid = localStorage.getItem('active_loginId');
same here ( `getFromStorage()` )

2023-10-18 04:40 UTC, shayan-deriv commented on src/utils/storage.ts
> +    // if (!active_loginid || !accounts) return;
can we remove these if we don't need them?

2023-10-18 04:43 UTC, shayan-deriv commented on src/api/hooks/useAuthorize.ts
> +            const active_loginid = localStorage.getItem('active_loginId');
same here ( `getFromStorage()` ). if you think we don't need `getFromStorage()` maybe we can remove it.

2023-10-18 04:57 UTC, shayan-deriv commented on src/api/hooks/useAuthorize.ts
> +                invalidate('authorize');
I have a question since I haven't work much with react-query. what will happen exactly when we call invlidate ?

2023-10-18 04:59 UTC, shayan-deriv commented on src/api/hooks/useAuthorize.ts
> +                invalidate('authorize');
it will refetch data for the new `loginid`?

2023-10-18 05:12 UTC, henry-deriv commented on src/utils/storage.ts
> +    const active_loginid = localStorage.getItem('active_loginId');
We should just remove getFromStorage lol. It's abstracting a simple line of code for no reason.

2023-10-18 05:41 UTC, shayan-deriv commented on src/utils/storage.ts
> +    const active_loginid = localStorage.getItem('active_loginId');
I agree. please remove

2023-10-18 10:01 UTC, niloofar-deriv commented on tsconfig.json
>      }
```suggestion
    "Types/*": ["types/*"]
    }
```

You need to add this path

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +import React from 'react';
Do we need importing React?

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +import ErrorBoundary from './components/common/error-boundary';
```suggestion
import ErrorBoundary from 'Components/common/error-boundary';
```

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +import Layout from './components/layout';
```suggestion
import Layout from 'Components/layout';
```

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +import useLogin from './api/hooks/useLogin';
```suggestion
import useLogin from 'Api/hooks/useLogin';
```

Can we add this to our vite and ts config, so we can import it like this

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +            <Layout is_logged_in={is_logged_in}>App</Layout>
Why we are passing is_logged_in as a props? can't we just use this custom hook inside the layout?

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +            <Layout is_logged_in={is_logged_in}>App</Layout>
IMO we don't need to pass it as a props.

2023-10-19 06:00 UTC, niloofar-deriv commented on src/App.tsx
> +            <Layout is_logged_in={is_logged_in}>App</Layout>
Also it will increase the code complexity

2023-10-20 06:57 UTC, hasan-deriv commented on package.json
> +    "lint-staged": "^15.0.1",
Shouldn't it be dev dependency?

2023-10-20 06:57 UTC, hasan-deriv approved these changes

2023-10-20 07:46 UTC, henry-deriv commented on src/App.tsx
> +import React from 'react';
Either linter or pre commit checks were complaining i believe.

2023-10-20 07:47 UTC, henry-deriv commented on src/App.tsx
> +            <Layout is_logged_in={is_logged_in}>App</Layout>
yup can remove

2023-10-20 07:47 UTC, henry-deriv commented on package.json
> +    "lint-staged": "^15.0.1",
I pulled master and it came into my PR. I dont remember who added it. @shayan-deriv @niloofar-deriv  ?

2023-10-23 02:17 UTC, shayan-deriv commented on package.json
> +    "lint-staged": "^15.0.1",
yes should be devDep. 
cc: @niloofar-deriv

2023-10-23 02:26 UTC, henry-deriv commented on package.json
> +    "lint-staged": "^15.0.1",
ok i will resolve it here

2023-10-23 06:11 UTC, matin-deriv requested changes

2023-10-23 06:11 UTC, matin-deriv commented on src/utils/websocket/config.ts
> +export const domain_app_ids = {
Can we move this to a constant file!

2023-10-23 06:11 UTC, matin-deriv commented on src/utils/websocket/config.ts
> +        app_id = 22169;
What do you think about accessing the app_ids from a constant file which is a single source of truth?

2023-10-23 06:11 UTC, matin-deriv commented on src/utils/utility.ts
> +import useAuthorize from '../api/hooks/useAuthorize';
```suggestion
import useAuthorize from 'Api/hooks/useAuthorize';
```

2023-10-23 06:11 UTC, matin-deriv commented on tsconfig.json
> +      "Hooks/*": ["hooks/*"],
Do you need to replace this with `Api`?

2023-10-23 06:11 UTC, matin-deriv commented on tsconfig.json
> +    /* Absoloute path */
```suggestion
    /* Absolute path */
```

2023-10-23 06:11 UTC, matin-deriv commented on src/utils/websocket/config.ts
> +    const server = is_real ? 'green' : 'blue';
Would be nice to move the servers to a constant file as well 🙏🏼

2023-10-23 06:11 UTC, matin-deriv commented on src/utils/websocket/APIProvider.tsx
> +    const language = 'EN'; // Need to use the language from the app context.
You can import `DEFAULT_LANGUAGE` from the constant file `translations.ts`

2023-10-23 06:13 UTC, henry-deriv commented on tsconfig.json
> +      "Hooks/*": ["hooks/*"],
ah i thought i did

2023-10-23 07:29 UTC, henry-deriv commented on src/utils/websocket/config.ts
> +        app_id = 22169;
👍

2023-10-23 07:56 UTC, matin-deriv commented on src/utils/login.ts
> +    const language = 'en';
Is this always `en`? should we get this from the localstorage or use the default language?

2023-10-23 08:04 UTC, maryia-deriv requested changes
just 1 question, the rest LGTM👍🏻

2023-10-23 08:04 UTC, maryia-deriv commented on src/components/layout/header/login-logout/LoginLogoutButton.tsx
> +    return <a href={loginUrl()}>login</a>;
@henry-deriv  shouldn't we use the Button component from components/ui here? :)

2023-10-23 08:07 UTC, matin-deriv commented on src/components/layout/header/login-logout/LoginLogoutButton.tsx
> +    return <a href={loginUrl()}>login</a>;
@maryia-deriv I believe this is just a temp button to test the login and logout, we will implement the header later on! still a WIP 😄

2023-10-23 08:13 UTC, henry-deriv commented on src/utils/login.ts
> +    const language = 'en';
Actually language change is not handled yet. Will do when we have language switcher. Will pull from local storage but if local storage value is empty we'll default to DEFAULT_LANGUAGE

2023-10-23 08:16 UTC, maryia-deriv approved these changes

2023-10-23 08:16 UTC, matin-deriv submitted a review, later dismissed

2023-10-23 09:35 UTC, niloofar-deriv commented on src/api/hooks/utils.ts
> +export const getQueryKeys = (name: string, props?: Record<string, unknown>) => {
```suggestion
export const getQueryKeys = <T extends object>(name: string, props?: Record<string, T>) => {
```

🤔

2023-10-23 09:35 UTC, niloofar-deriv commented on src/api/hooks/useResponsive.ts
This is not related to the apis hook, I guess it's better to remove the file, later if we need that we can recreate it under `src/hooks` folder!

2023-10-24 00:40 UTC, henry-deriv commented on src/api/hooks/utils.ts
> +export const getQueryKeys = (name: string, props?: Record<string, unknown>) => {
doesnt work.

2023-10-24 02:32 UTC, niloofar-deriv approved these changes

2023-10-24 02:36 UTC, matin-deriv submitted a review, later dismissed

2023-10-24 05:54 UTC, ali-hosseini-deriv requested changes
The CI is failing due to wrong type definition/usage.
please check it.

2023-10-24 06:36 UTC, shayan-deriv commented on src/api/hooks/useLogin.ts
> +    const client_account = readLoginQueryParams();
```suggestion
    const client_account_params = readLoginQueryParams();
```
just for being more clear

2023-10-24 06:36 UTC, shayan-deriv commented on src/api/hooks/useLogin.ts
> +    const { data: account_list } = useAuthorize();
```suggestion
    const { data: client_info } = useAuthorize();
```
same here

2023-10-24 06:59 UTC, shayan-deriv commented on src/utils/utility.ts
> +                    }
```suggestion
                   active_loginid = account[param] ?? '';
```
can we change it for now? 
I see that there is a TODO for the `else if` block so we can add more logics but for now I think we can remove it. what do u think @henry-deriv ?

2023-10-24 07:21 UTC, henry-deriv commented on src/utils/utility.ts
> +                    }
@shayan-deriv i changed it. Take a look!

2023-10-24 07:45 UTC, shayan-deriv commented on src/api/hooks/useMutation.ts
what are we using this for ? 🤔  @henry-deriv

2023-10-24 07:45 UTC, shayan-deriv commented on src/utils/utility.ts
> +                    }
thanks man. LGTM

2023-10-24 07:48 UTC, shayan-deriv commented on src/api/hooks/useMutation.ts
ignore my question 😄 figured it out

2023-10-24 07:56 UTC, shayan-deriv approved these changes

2023-10-24 07:58 UTC, matin-deriv approved these changes

2023-10-25 02:05 UTC, niloofar-deriv approved these changes

2023-10-25 02:33 UTC, merged