Nada/webrel 1482/header layout
deriv-com/smarttrader_archived pull request #27
Opened 2023-10-26 07:45 UTC by nada-deriv

<img width="1202" alt="Screenshot 2023-10-26 at 11 11 51 AM" src="https://github.com/deriv-com/smarttrader/assets/122768621/14ca0799-6129-4add-a6d7-5a6033a3a110">
<img width="1202" alt="Screenshot 2023-10-26 at 11 11 59 AM" src="https://github.com/deriv-com/smarttrader/assets/122768621/bde8019d-e71b-426d-9abc-7ffc3a52f813">
<img width="546" alt="Screenshot 2023-10-26 at 11 12 14 AM" src="https://github.com/deriv-com/smarttrader/assets/122768621/26a1fce4-ac7c-49a1-9d71-6a38aa74fb1e">
<img width="570" alt="Screenshot 2023-10-26 at 11 12 20 AM" src="https://github.com/deriv-com/smarttrader/assets/122768621/4736225c-023a-49fa-874f-cf7c6998dbe9">

2023-10-26 07:46 UTC, nada-deriv commented
need to fix few styles. added the placeholders for now.

2023-10-27 03:10 UTC, henry-deriv commented on src/components/layout/header/account-settings/index.tsx
> +        <img src='/images/pages/header/ic-user-outline.svg' height={20} width={20} className='cursor-pointer' />
need to wrap in <a></a>

2023-10-27 03:14 UTC, henry-deriv commented on src/components/layout/header/logged-in-state/index.tsx
> +            <Button size='sm' className='mx-[1.6rem] text-[14px] sm:hidden xs:hidden'>
probably a tag right?

2023-10-27 03:36 UTC, hasan-deriv requested changes

2023-10-27 03:36 UTC, hasan-deriv commented on src/components/layout/header/index.tsx
> +                    )}
```suggestion
                    {is_logged_in && <Tab />}
```

2023-10-27 03:36 UTC, hasan-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
```suggestion
                    <button onClick={() => setIsLoggedIn(false)} className='flex h-full items-center'>
                        <LoggedInState />
                    </button>
                ) : (
                    <button onClick={() => setIsLoggedIn(true)} className='flex h-full items-center'>
                        <LoggedOutState />
                    </button>
```

2023-10-27 03:36 UTC, hasan-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
Attaching `onClick` to a `div` is not wrong, but consider using semantic elements for better accessibility. It would be better to use `button` here.

2023-10-27 03:36 UTC, hasan-deriv commented on src/components/layout/header/logged-out-state/index.tsx
> +            <Button className=' text-fontSize-xxl mr-1.5 border-none bg-white px-base text-primary hover:bg-red-50'>
making a new variant for it would be good.

2023-10-27 03:36 UTC, hasan-deriv commented on tailwind.config.js
> +                xs: { max: '575px' },
Aren't we going to do mobile-first approach?

2023-10-27 05:11 UTC, nada-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
but loggedinstate and loggedoutstate are not buttons.. they are components

2023-10-27 05:11 UTC, nada-deriv commented on src/components/layout/header/logged-out-state/index.tsx
> +            <Button className=' text-fontSize-xxl mr-1.5 border-none bg-white px-base text-primary hover:bg-red-50'>
yeah.. couldn't find the variant for login button as well.. need to add few styles as well to tailwindconfig

2023-10-27 05:12 UTC, nada-deriv commented on src/components/layout/header/logged-in-state/index.tsx
> +            <Button size='sm' className='mx-[1.6rem] text-[14px] sm:hidden xs:hidden'>
yeah.. tag can be wrapped on the child.. didn't do it for now as the redirection is not handled now.

2023-10-27 13:11 UTC, henry-deriv commented
Wait i just noticed all the components are written in `index.tsx` i think it'll be a lot more discoverable/searchable if you name the files same as the component definition. Then,  export out the component from `index.ts`. Ignore the scss file.
<img width="224" alt="Screenshot 2023-10-27 at 9 10 07 PM" src="https://github.com/deriv-com/smarttrader/assets/118344354/b7bcdb4e-9045-4d79-89eb-d0698ec0218a">

and inside index.tsx

`export { default as DesktopWalletsList } from './DesktopWalletsList';`

2023-10-27 13:15 UTC, henry-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
i have a hard time visualizing what loggedInstate and loggedOutState are? 

Can you show us the picture of it?

2023-10-30 03:17 UTC, hasan-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
Then we might change the markup.

2023-10-30 04:25 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/index.tsx
> +        <img src='/images/pages/header/ic-user-outline.svg' height={20} width={20} className='cursor-pointer' />
Please add alt msg to the img

2023-10-30 04:25 UTC, niloofar-deriv commented on src/components/layout/header/account-switcher/index.tsx
> +        <img src='/images/pages/header/ic-currency-virtual.svg' />
pls add alt msg

2023-10-30 04:25 UTC, niloofar-deriv commented on src/components/layout/header/account-switcher/index.tsx
> +        <img src='/images/pages/header/ic-chevron-down.svg' />
pls add alt msg

2023-10-30 04:25 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} />
pls add alt msg

2023-10-30 04:25 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +            <>
Do u need this Fragment?

2023-10-30 05:13 UTC, nada-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
wait.. forgot to mention.. this wrapper div will be removed.. i just put it there to locally implement the login and logout states.. actual onclick will be handled by the login button inside the loggedoutstate component.. and i think logout is in account settings or account switcher..

2023-10-30 08:53 UTC, nada-deriv commented on src/components/layout/header/account-settings/index.tsx
> +        <img src='/images/pages/header/ic-user-outline.svg' height={20} width={20} className='cursor-pointer' />
do we need translation for alt value?

2023-10-30 09:00 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/index.tsx
> +        <img src='/images/pages/header/ic-user-outline.svg' height={20} width={20} className='cursor-pointer' />
For deriv.com project SEO team told me that we need it
but here I think we don't need that, also we don't have translations for our alt msgs

2023-10-30 09:16 UTC, nada-deriv commented on src/components/layout/header/index.tsx
> +                    </div>
@henry-deriv  the logged out state is the one with signup and login buttons.. and the loggedinstate has the deposit buton, account switcher, account settings and notification icons.. i just broke everything into smaller components.

2023-11-03 02:43 UTC, hasan-deriv commented on src/components/layout/header/logged-out-state/LoggedOutState.tsx
> +            </Button>
These button components need **asChild** props.

2023-11-03 02:43 UTC, hasan-deriv commented on src/components/layout/header/tab/tab.tsx
Tab component is merged in main. Please use that 🙏

2023-11-03 05:26 UTC, nada-deriv commented on src/components/layout/header/tab/tab.tsx
the tab component i used is a different one.. for the 'cashier' 'report' 'traders hub' tabs.. i think i should probably give a different name

2023-11-06 02:35 UTC, hasan-deriv commented on src/components/layout/header/tab/tab.tsx
Got it. It's navigation

2023-11-06 03:19 UTC, niloofar-deriv requested changes

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/AccountSettings.tsx
> +const AccountSettings = () => (
AFAIK we don't have any card for this, so I guess you need to add the redirection's link to the account setting here

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/AccountSettings.tsx
> +            alt='account settings'
```suggestion
            alt='Account settings'
```

nit

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/AccountSettings.tsx
> +            className='cursor-pointer'
If you add the href to the `a` tag you won't need this class so you can remove this
```suggestion
            
```

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/AccountSettings.tsx
> +const AccountSettings = () => (
Also you need to add tests too 🙏

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/AccountSettings.tsx
> +const AccountSettings = () => (
Base on our new folders structure you can now remove the index and folder and move the file to the header folder

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-settings/index.ts
> +import AccountSettings from './AccountSettings';
You don't need this you can remove that

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/account-switcher/index.ts
> +import AccountSwitcher from './AccountSwitcher';
Same for this you can delete this index and the folder and move the AccountSwitcher to the header folder

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +    const [is_logged_in, setIsLoggedIn] = useState(false);
```suggestion
    const [isLoggedIn, setIsLoggedIn] = useState(false);
```

Code smell

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} alt='hamburger menu' />
```suggestion
                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} alt='Hamburger menu' />
```

nit

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +                    {is_logged_in && <Section />}
```suggestion
                    {isLoggedIn && <Section />}
```

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/index.tsx
> +            {is_logged_in ? (
```suggestion
            {isLoggedIn ? (
```

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/platform-switcher/index.ts
> +import PlatformSwitcher from './PlatformSwitcher';
Same for this you can remove the index and move the file to the Header folder

2023-11-06 03:19 UTC, niloofar-deriv commented on src/components/layout/header/notifications/index.ts
> +import Notifications from './Notifications';
same for this

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/ui/button/index.tsx
> +                className: 'bg-primary hover:bg-primary-hover focus:bg-primary-hover cursor-pointer',
Do you need this class? I believe by passing the onClick the cursor would be pointer 🤔  
```suggestion
                className: 'bg-primary hover:bg-primary-hover focus:bg-primary-hover',
```

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/ui/button/index.tsx
> +                tertiary: 'border-none hover:bg-tertiary-hover text-primary cursor-pointer',
Same for this
```suggestion
                tertiary: 'border-none hover:bg-tertiary-hover text-primary',
```

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/layout/header/SectionTab.tsx
> +const SectionTabItem = ({ alt, label, imageUrl, className }: TSectionTabItemProps) => {
Could u pls move this to a separate file 🙏

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/layout/header/__test__/LoggedOutState.test.tsx
> +    it('should render the logged out state', () => {
```suggestion
    it('should render the logged in state', () => {
```

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/layout/header/Header.tsx
> +                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} alt='Hamburger menu' />
Could u pls add the alt message 🙏

2023-11-07 04:48 UTC, niloofar-deriv commented on src/components/layout/header/Header.tsx
> +            {is_logged_in ? (
```suggestion
<div className='flex h-full items-center'>
      {is_logged_in ?  <LoggedInState /> : <LoggedOutState />}
</div>
```

2023-11-07 05:23 UTC, nada-deriv commented on src/components/layout/header/Header.tsx
> +                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} alt='Hamburger menu' />
but its already there. do you mean changing it from 'hamburger menu' to something else?

2023-11-07 05:32 UTC, nada-deriv commented on src/components/ui/button/index.tsx
> +                className: 'bg-primary hover:bg-primary-hover focus:bg-primary-hover cursor-pointer',
no. giving onlick is not bringing the cursor change.

2023-11-07 06:01 UTC, niloofar-deriv commented on src/components/layout/header/Header.tsx
> +                    <img src='/images/pages/header/ic-hamburger.svg' height={20} width={20} alt='Hamburger menu' />
Sorry I didn't notice that 🙏

2023-11-07 06:03 UTC, niloofar-deriv approved these changes
LGTM 👍

2023-11-07 06:10 UTC, balakrishna-deriv approved these changes

2023-11-07 06:10 UTC, merged