henry/feat: useTicksHistory and useActiveSymbols hooks
deriv-com/smarttrader_archived pull request #43
Opened 2023-11-16 06:57 UTC by henry-deriv

2023-11-16 10:04 UTC, hasan-deriv requested changes

2023-11-16 10:04 UTC, hasan-deriv commented on src/components/layout/Layout.tsx
> +    const [symbol, setSymbol] = useState('R_50');
`symbol` is javascript's reserves word. We shouldn't use this

2023-11-16 10:04 UTC, hasan-deriv commented on src/api/hooks/useSubscription.ts
> +    const [isSubscribed, setSubscribed] = useState(false);
```suggestion
    const [isSubscribed, setIsSubscribed] = useState(false);
```

2023-11-17 02:43 UTC, ahmadtaimoor-deriv commented on src/api/hooks/useTicksHistory.ts
> +                    granularity: !granularity ? undefined : granularity,
suggestion:
granularity: granularity || undefined,

2023-11-17 03:15 UTC, ahmadtaimoor-deriv commented on src/components/layout/header/__test__/Header.test.tsx
Not exactly related to this PR  
I think we can create the mock in different mock file and just import it here rather then creating mock in each test file.(Can ignore)

2023-11-17 03:15 UTC, ahmadtaimoor-deriv commented on src/components/layout/Layout.tsx
> +            if (e.target.name === 'granularity') setGranularity(Number(e.target.value) as TParams);
I would like to  know why used Number and not parseInt ?

2023-11-17 03:18 UTC, henry-deriv commented on src/components/layout/Layout.tsx
> +            if (e.target.name === 'granularity') setGranularity(Number(e.target.value) as TParams);
i just needed to make sure e.target.value is number instead of a string

2023-11-17 03:19 UTC, henry-deriv commented on src/components/layout/header/__test__/Header.test.tsx
Yeah that would be great. I just added variable that was needed to make the test pass

2023-11-17 06:40 UTC, niloofar-deriv commented on src/api/hooks/useActiveSymbols.ts
> +    const { is_logged_in, isAuthorized } = useLogin();
I know it's out of the scope of this card but could u pls update this like this 🙏 
```suggestion
    const { isLoggedIn, isAuthorized } = useLogin();
```

2023-11-17 06:40 UTC, niloofar-deriv commented on src/api/hooks/useActiveSymbols.ts
> +    const { data: active_symbols, ...rest } = useQuery('active_symbols', {
Code smell 
```suggestion
    const { data: activeSymbols, ...rest } = useQuery('active_symbols', {
```

2023-11-17 06:40 UTC, niloofar-deriv commented on src/api/hooks/useActiveSymbols.ts
> +    const modified_active_symbols = useMemo(
```suggestion
    const modifiedActiveSymbols = useMemo(
```

2023-11-17 06:41 UTC, niloofar-deriv commented on src/components/layout/Layout.tsx
> +                    <option value='R_50'>R_50</option>
Are these example?
if not can we map them instead of repeating them

2023-11-17 06:55 UTC, niloofar-deriv commented on src/components/layout/Layout.tsx
> +            <div>
If these are not example can we move them to a separate file so we won't make the component big and complicated

2023-11-20 01:59 UTC, henry-deriv commented on src/components/layout/Layout.tsx
> +                    <option value='R_50'>R_50</option>
this is just to see if the hook is working

2023-11-20 02:00 UTC, henry-deriv commented on src/components/layout/Layout.tsx
> +            <div>
This is just for testing purpose

2023-11-20 02:12 UTC, niloofar-deriv commented on src/api/hooks/useLogin.ts
> +    return { is_logged_in, isAuthorized: isSuccess };
For fixing the eslint error you need to change is_logged_in here too.
```suggestion
    return { isLoggedIn, isAuthorized: isSuccess };
```

2023-11-20 04:21 UTC, shayan-deriv approved these changes
other than `isLoggedIn` issue, the rest LGTM.

2023-11-20 07:07 UTC, niloofar-deriv approved these changes

2023-11-20 07:14 UTC, balakrishna-deriv approved these changes

2023-11-20 07:16 UTC, merged