fix: files moved
deriv-com/smarttrader_archived pull request #8
Opened 2023-10-08 15:24 UTC by mayuran-deriv

2023-10-09 02:09 UTC, hasan-deriv requested changes
Fonts should be added in public directory.

2023-10-09 03:40 UTC, matin-deriv requested changes
I believe majority of the files are not needed and all the static files need to be moved to the public folder.

You can check out this PR for the unnecessary files: https://github.com/deriv-com/binary-static/pull/558

2023-10-11 00:53 UTC, henry-deriv commented on public/images/pages/header/ic-brand-dbot.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35"><g fill="none" fill-rule="evenodd"><rect width="35" height="35" fill="#FF6444" fill-rule="nonzero" rx="6"/><path d="M13.72 13.26a.845.84
- ic-brand-binarybot
- ic-brand-dbot
- ic-brand-dtrader

are old logos.

You are mimssing ic-brand-smarttrader

2023-10-11 00:58 UTC, henry-deriv commented on public/images/pages/footer/linkedin.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60"><path d="M46.837 44.137V32.425c0-6.275-3.35-9.195-7.816-9.195-3.603 0-5.218 1.983-6.118 3.374V23.71h-6.79c.09 1.917 0 20.427 0 20.427h6.79V
I've never seen the following social media icons in the footer. Also, we'll try to match app.deriv.com footer so u'll have to find those icons as well.

- linkedin
- reddit
- telegram
- twitter
- youtube
need to be removed

2023-10-11 01:01 UTC, henry-deriv commented
<img width="368" alt="Screenshot 2023-10-11 at 9 00 14 AM" src="https://github.com/deriv-com/smarttrader/assets/118344354/a29e79df-c34b-4cf5-bcc0-518af6c57210">


`trade-explanation` svgs are missing. There should be one for each supported language.

2023-10-11 01:03 UTC, henry-deriv commented on public/images/pages/header/logo_smart_trader.svg
> +<svg width="33" height="33" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M6.07 0h20.24a6.07 6.07 0 016.07 6.07v20.24a6.07 6.07 0 01-6.07 6.07H6.07A6.07 6.07 0 010 26
needs to be rebranded logo

2023-10-11 01:05 UTC, henry-deriv commented on public/images/pages/settings/2fa.svg
> +<svg width="126" height="126" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><path d="M2 124h122V2H2v122zM0 0h126v126H0V0z" fill="#CDCCCB" fill-rule="nonzero"/><path fill="#F2F
We don't have settings. So the whole folder can be removed.

2023-10-11 01:07 UTC, henry-deriv commented on public/images/social/apple.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M17.294 12.473c0-2.46 2.063-3.65 2.142-3.73-1.19-1.665-2.935-1.903-3.57-1.983-1.508-.158-3.015.873-3.73.873-.793 0-1.983-.873-3
no need for social icons

2023-10-11 01:07 UTC, henry-deriv commented on public/images/common/email_sent.svg
> +<svg width="152" height="58" viewBox="0 0 152 58" xmlns="http://www.w3.org/2000/svg"><title>message</title><g fill-rule="nonzero" fill="none"><path d="M151.932 4.313a4.315 4.315 0 0 0-4.314-4.299h-.0
wheres this used?

2023-10-11 01:07 UTC, henry-deriv commented on public/images/common/globe-with_logo.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 834 840.14"><defs><linearGradient id="linear-gradient" x1="286.19" y1="635.02" x2="275.15" y2="704.65" gradientUn
dont think this is used

2023-10-11 01:11 UTC, henry-deriv commented
`.png` files can be removed.

2023-10-11 01:13 UTC, henry-deriv commented on public/images/common/password_hide.svg
> +<svg width="16" height="16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14.177 2.118a.5.5 0 0 1 .646.764l-2.048 1.732A7.924 7.924 0 0 1 15.333 8c-1.153 2.927-4 5-7.333 5a7.83 7.83 0 0 1-
password_show
password_hide

not needed

2023-10-11 01:14 UTC, henry-deriv commented on public/images/pages/contact/banner-bg.svg
> +<svg width="320" height="320" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><path id="a" d="M0 0h320v320H0z"/></defs><g fill="none" fill-rule="evenodd"><mask id=
dont think this is used

2023-10-12 08:20 UTC, mayuran-deriv commented on public/images/common/globe-with_logo.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 834 840.14"><defs><linearGradient id="linear-gradient" x1="286.19" y1="635.02" x2="275.15" y2="704.65" gradientUn
we need this I saw this in the current project

2023-10-13 06:29 UTC, henry-deriv commented on public/images/pages/contact/content-icon.svg
> +<svg width="64" height="64" xmlns="http://www.w3.org/2000/svg"><path d="M50 4a6 6 0 016 6v44a6 6 0 01-6 6H14a6 6 0 01-6-6V10a6 6 0 016-6zm0 4H14a2 2 0 00-2 2v44a2 2 0 002 2h36a2 2 0 002-2V10a2 2 0 00
where is this used

2023-10-13 06:30 UTC, henry-deriv commented on public/images/pages/contact/ticket-icon.svg
> +<svg width="60" height="60" xmlns="http://www.w3.org/2000/svg"><g fill="#000" fill-rule="nonzero"><path d="M27 18.997h6a1 1 0 1 0 0-2h-6a1 1 0 1 0 0 2zM42 32.997h-6a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2zM18
where is this used

2023-10-13 06:32 UTC, henry-deriv commented
<img width="363" alt="Screenshot 2023-10-13 at 2 29 23 PM" src="https://github.com/deriv-com/smarttrader/assets/118344354/f33d17f4-3c08-474b-b92d-2a00e856cac9">

lets try to get the missing ones. Except sun svg icon for changing theme

2023-10-13 07:54 UTC, matin-deriv requested changes

2023-10-13 07:54 UTC, matin-deriv commented on public/images/social/facebook.svg
> +<svg width="24" height="24" xmlns="http://www.w3.org/2000/svg"><g fill="none" fill-rule="evenodd"><rect fill="#3B5998" width="24" height="24" rx="2"/><path d="M12.877 24h3.752v-9.995h2.814L20 10.882h
Where do we use social icons?

2023-10-13 07:54 UTC, matin-deriv commented on public/images/pages/header/ic-mt5-advanced.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><g fill="none" fill-rule="evenodd"><circle cx="32" cy="32" r="32" fill="#C7E5E5" fill-rule="nonzero"/><path fill="#84ABAE" fill-rule="no
Certain icons such as MT5 ones are not needed! you can remove them 🙏🏼

2023-10-13 07:57 UTC, mayuran-deriv commented on public/images/social/apple.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M17.294 12.473c0-2.46 2.063-3.65 2.142-3.73-1.19-1.665-2.935-1.903-3.57-1.983-1.508-.158-3.015.873-3.73.873-.793 0-1.983-.873-3
@matin-deriv i removed social icons

2023-10-13 10:12 UTC, mayuran-deriv commented on public/images/social/apple.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"><path d="M17.294 12.473c0-2.46 2.063-3.65 2.142-3.73-1.19-1.665-2.935-1.903-3.57-1.983-1.508-.158-3.015.873-3.73.873-.793 0-1.983-.873-3
added again

2023-10-16 08:56 UTC, henry-deriv commented on public/images/common/ic_dtrader.svg
> +<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
rebranded icons need to be minified

2023-10-16 09:48 UTC, henry-deriv approved these changes
LGTM

2023-10-17 03:05 UTC, matin-deriv approved these changes

2023-10-17 03:05 UTC, merged